### ISSUE TITLE
Modify the program to accept kwarg instead of args

### ISSUE THREAD

**Issue by akhilputhiry** [EdwinLingson/python-exercises#1]
https://github.com/EdwinLingson/python-exercises/blob/db9b7a67772ea1cb119fc248d5dcf9f173eedd8d/Gates.py#L61

Now you can use the program using args `program.py 1 2`

Instead of that i want to use kwarg `program.py --gate=and --input1=1 --input2=0`

**Comment by EdwinLingson** [comment]
Updated it
